Use known method to load environment variables

diff --git a/.github/workflows/qualer-check.yml b/.github/workflows/qualer-check.yml
--- a/.github/workflows/qualer-check.yml
+++ b/.github/workflows/qualer-check.yml
@@ -1,8 +1,12 @@
-name: Qualer Pre-Merge Validation
+name: Pre-Merge Validation
 
 on:
   workflow_call:
     inputs:
+      ENV_FILE_PATH:
+        required: false
+        type: string
+        default: ".env"
       repo_name:
         required: true
         type: string
@@ -34,6 +38,22 @@ jobs:
 
       - name: Display environment variables (for debugging)
         run: env | sort
+
+      - name: Validate required environment variables
+        run: |
+          REQUIRED_VARS=("SOP_ID" "DOC_ID" "DOC_TITLE" "DOC_DETAILS")
+          MISSING_VARS=()
+          
+          for VAR in "${REQUIRED_VARS[@]}"; do
+            if [[ -z "${!VAR}" ]]; then
+              MISSING_VARS+=("$VAR")
+            fi
+          done
+
+          if [[ ${#MISSING_VARS[@]} -ne 0 ]]; then
+            echo "Error: Missing required environment variables: ${MISSING_VARS[*]}"
+            exit 1
+          fi
 
       - name: Validate Secrets
         run: |
diff --git a/.github/workflows/qualer-upload-release.yml b/.github/workflows/qualer-upload-release.yml
--- a/.github/workflows/qualer-upload-release.yml
+++ b/.github/workflows/qualer-upload-release.yml
@@ -35,6 +35,22 @@ jobs:
       - name: Display environment variables (for debugging)
         run: env | sort
 
+      - name: Validate required environment variables
+        run: |
+          REQUIRED_VARS=("SOP_ID" "DOC_ID" "DOC_TITLE" "DOC_DETAILS")
+          MISSING_VARS=()
+          
+          for VAR in "${REQUIRED_VARS[@]}"; do
+            if [[ -z "${!VAR}" ]]; then
+              MISSING_VARS+=("$VAR")
+            fi
+          done
+
+          if [[ ${#MISSING_VARS[@]} -ne 0 ]]; then
+            echo "Error: Missing required environment variables: ${MISSING_VARS[*]}"
+            exit 1
+          fi
+
       - name: Validate Secrets
         run: |
           if [[ -z "${{ secrets.QUALER_EMAIL }}" || -z "${{ secrets.QUALER_PASSWORD }}" ]]; then
